In [1]:
import numpy as np
import pandas as pd

In [58]:
df = pd.DataFrame({'emp_id':[1,2,3,4,5],
                   'emp_name':['a','b','c','d','e']})

In [33]:
df1 = pd.DataFrame({'emp_id':[2,3,4,5],
                   'sal':np.random.randint(24000,40000,4)})

In [59]:
df

   emp_id emp_name
0       1        a
1       2        b
2       3        c
3       4        d
4       5        e

In [60]:
df1

   emp_id    sal
0       2  29811
1       3  31553
2       4  31367
3       5  37462

In [51]:
a = pd.concat([df,df1],axis=0,keys=['df','df1'])

In [52]:
a

      emp_id emp_name      sal
df  0      1        a      NaN
    1      2        b      NaN
    2      3        c      NaN
    3      4        d      NaN
    4      5        e      NaN
df1 0      2      NaN  29811.0
    1      3      NaN  31553.0
    2      4      NaN  31367.0
    3      5      NaN  37462.0

In [49]:
b = pd.concat([df,df1],axis=1,keys=['df','df1'])

In [50]:
b

      df             df1
  emp_id emp_name emp_id      sal
0      1        a    2.0  29811.0
1      2        b    3.0  31553.0
2      3        c    4.0  31367.0
3      4        d    5.0  37462.0
4      5        e    NaN      NaN

In [22]:
df2 =  pd.DataFrame({'jan':[1,1,1,1,0,1,1,0],
                   'feb':[1,0,1,0,1,1,0,1],
                   'mar':[0,1,0,1,0,1,0,1]})

df3 =  pd.DataFrame({'jan':[0,1,0,1,0,0,1,0],
                   'feb':[1,0,1,0,1,1,0,0],
                   'mar':[0,1,1,0,0,0,0,0],
                     'apr':[0,1,1,0,0,0,0,0]})

In [47]:
df2

   jan  feb  mar
0    1    1    0
1    1    0    1
2    1    1    0
3    1    0    1
4    0    1    0
5    1    1    1
6    1    0    0
7    0    1    1

In [48]:
df3

   jan  feb  mar  apr
0    0    1    0    0
1    1    0    1    1
2    0    1    1    1
3    1    0    0    0
4    0    1    0    0
5    0    1    0    0
6    1    0    0    0
7    0    0    0    0

In [63]:
pd.merge(df,df1,on='emp_id',how='outer')

   emp_id emp_name      sal
0       1        a      NaN
1       2        b  29811.0
2       3        c  31553.0
3       4        d  31367.0
4       5        e  37462.0

In [64]:
pd.merge(df,df1,on='emp_id',how='inner')

   emp_id emp_name    sal
0       2        b  29811
1       3        c  31553
2       4        d  31367
3       5        e  37462

In [65]:
pd.merge(df,df1,on='emp_id',how='left')

   emp_id emp_name      sal
0       1        a      NaN
1       2        b  29811.0
2       3        c  31553.0
3       4        d  31367.0
4       5        e  37462.0

In [66]:
pd.merge(df,df1,on='emp_id',how='right')

   emp_id emp_name    sal
0       2        b  29811
1       3        c  31553
2       4        d  31367
3       5        e  37462

In [68]:
pd.merge(df,df1,how='cross')

    emp_id_x emp_name  emp_id_y    sal
0          1        a         2  29811
1          1        a         3  31553
2          1        a         4  31367
3          1        a         5  37462
4          2        b         2  29811
5          2        b         3  31553
6          2        b         4  31367
7          2        b         5  37462
8          3        c         2  29811
9          3        c         3  31553
10         3        c         4  31367
11         3        c         5  37462
12         4        d         2  29811
13         4        d         3  31553
14         4        d         4  31367
15         4        d         5  37462
16         5        e         2  29811
17         5        e         3  31553
18         5        e         4  31367
19         5        e         5  37462

In [ ]:
df.set

In [69]:
df.join(df1,how='inner')

ValueError: columns overlap but no suffix specified: Index(['emp_id'], dtype='object')